# Generated by Django 5.2.3 on 2026-01-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm_dashboard", "0004_alter_employee_share_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="share_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
