# Generated by Django 5.2.3 on 2026-01-11 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="applied_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
