# Generated by Django 5.2.3 on 2026-01-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm_dashboard", "0003_announcement_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="share_code",
            field=models.CharField(max_length=20),
        ),
    ]
